### ISSUE TITLE
RJGit::Commit#parents NullPointerException

### ISSUE THREAD

**Issue by Freaky** [repotag/rjgit#14]
jruby-9.0.0.0, rjgit 0.3.12.

Commit#parents reliably throws NullPointerException, like so:

        [125] pry(main)> RJGit::Repo.new('/repos/hardenedBSD.git').head.parents
        Java::JavaLang::NullPointerException:
        from org.eclipse.jgit.util.RawParseUtils.author(org/eclipse/jgit/util/RawParseUtils.java:567)
        [126] pry(main)> wtf
        Exception: Java::JavaLang::NullPointerException:
        --
        0: org.eclipse.jgit.util.RawParseUtils.author(org/eclipse/jgit/util/RawParseUtils.java:567)
        1: org.eclipse.jgit.revwalk.RevCommit.getAuthorIdent(org/eclipse/jgit/revwalk/RevCommit.java:396)
        2: java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:497)
        3: RUBY.initialize(/home/freaky/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rjgit-0.3.12/lib/commit.rb:27)
        4: RUBY.block in parents(/home/freaky/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rjgit-0.3.12/lib/commit.rb:41)

@jcommit.get_author_ident seems to be what's blowing up - possibly a JGit issue?

**Comment by bartkamphorst** [comment]
Thanks for reporting the issue @Freaky . It could potentially have something to do with your specific repository; can you also reproduce the issue with a freshly created repo?

**Comment by Freaky** [comment]
Yep.  Fresh repository made with git 2.4.6 and two commits blows up the same way.  So does every one of the other 38 repositories I have in /repos.

Currently bypassing the issue with `@jcommit.get_parents.map(&:get_name)`.

**Comment by bartkamphorst** [comment]
Thanks @Freaky . We just released a new RJGit gem version that bundles JGit 4.0.1. Could you give that one a try?

**Comment by Freaky** [comment]
Yep.  Same error :

        [1] pry(main)> RJGit::Repo.new('/repos/hardenedBSD.git').head.parents
        Java::JavaLang::NullPointerException:
        from org.eclipse.jgit.util.RawParseUtils.author(org/eclipse/jgit/util/RawParseUtils.java:567)
        [2] pry(main)> wtf?!?!
        Exception: Java::JavaLang::NullPointerException:
        --
         0: org.eclipse.jgit.util.RawParseUtils.author(org/eclipse/jgit/util/RawParseUtils.java:567)
         1: org.eclipse.jgit.revwalk.RevCommit.getAuthorIdent(org/eclipse/jgit/revwalk/RevCommit.java:401)
         2: java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:497)
         3: RUBY.initialize(/home/freaky/.rbenv/versions/jruby-9.0.1.0-SNAPSHOT/lib/ruby/gems/shared/gems/rjgit-4.0.1.0/lib/commit.rb:27)
         4: RUBY.block in parents(/home/freaky/.rbenv/versions/jruby-9.0.1.0-SNAPSHOT/lib/ruby/gems/shared/gems/rjgit-4.0.1.0/lib/commit.rb:41)
         5: org.jruby.java.proxies.ArrayJavaProxy.each(org/jruby/java/proxies/ArrayJavaProxy.java:154)
         6: org.jruby.RubyEnumerable.map(org/jruby/RubyEnumerable.java:800)
         7: RUBY.parents(/home/freaky/.rbenv/versions/jruby-9.0.1.0-SNAPSHOT/lib/ruby/gems/shared/gems/rjgit-4.0.1.0/lib/commit.rb:41)
         8: RUBY.<eval>((pry):1)
         9: org.jruby.RubyKernel.eval(org/jruby/RubyKernel.java:979)
        10: org.jruby.RubyBinding.eval(org/jruby/RubyBinding.java:139)
        11: RUBY.evaluate_ruby(/home/freaky/.rbenv/versions/jruby-9.0.1.0-SNAPSHOT/lib/ruby/gems/shared/gems/pry-0.10.1-java/lib/pry/pry_instance.rb:355)
        12: RUBY.handle_line(/home/freaky/.rbenv/versions/jruby-9.0.1.0-SNAPSHOT/lib/ruby/gems/shared/gems/pry-0.10.1-java/lib/pry/pry_instance.rb:323)
        13: RUBY.block in eval(/home/freaky/.rbenv/versions/jruby-9.0.1.0-SNAPSHOT/lib/ruby/gems/shared/gems/pry-0.10.1-java/lib/pry/pry_instance.rb:243)
        14: org.jruby.RubyKernel.catch(org/jruby/RubyKernel.java:1099)
        15: RUBY.block in eval(/home/freaky/.rbenv/versions/jruby-9.0.1.0-SNAPSHOT/lib/ruby/gems/shared/gems/pry-0.10.1-java/lib/pry/pry_instance.rb:242)
        16: org.jruby.RubyKernel.catch(org/jruby/RubyKernel.java:1099)
        17: RUBY.eval(/home/freaky/.rbenv/versions/jruby-9.0.1.0-SNAPSHOT/lib/ruby/gems/shared/gems/pry-0.10.1-java/lib/pry/pry_instance.rb:241)
        18: RUBY.block in repl(/home/freaky/.rbenv/versions/jruby-9.0.1.0-SNAPSHOT/lib/ruby/gems/shared/gems/pry-0.10.1-java/lib/pry/repl.rb:77)
        19: org.jruby.RubyKernel.loop(org/jruby/RubyKernel.java:1292)
        20: RUBY.repl(/home/freaky/.rbenv/versions/jruby-9.0.1.0-SNAPSHOT/lib/ruby/gems/shared/gems/pry-0.10.1-java/lib/pry/repl.rb:67)
        21: RUBY.block in start(/home/freaky/.rbenv/versions/jruby-9.0.1.0-SNAPSHOT/lib/ruby/gems/shared/gems/pry-0.10.1-java/lib/pry/repl.rb:38)
        22: org.jruby.RubyProc.call(org/jruby/RubyProc.java:308)
        23: RUBY.__with_ownership(/home/freaky/.rbenv/versions/jruby-9.0.1.0-SNAPSHOT/lib/ruby/gems/shared/gems/pry-0.10.1-java/lib/pry/input_lock.rb:61)
        24: RUBY.with_ownership(/home/freaky/.rbenv/versions/jruby-9.0.1.0-SNAPSHOT/lib/ruby/gems/shared/gems/pry-0.10.1-java/lib/pry/input_lock.rb:79)
        25: RUBY.start(/home/freaky/.rbenv/versions/jruby-9.0.1.0-SNAPSHOT/lib/ruby/gems/shared/gems/pry-0.10.1-java/lib/pry/repl.rb:38)
        26: RUBY.start(/home/freaky/.rbenv/versions/jruby-9.0.1.0-SNAPSHOT/lib/ruby/gems/shared/gems/pry-0.10.1-java/lib/pry/repl.rb:15)
        27: RUBY.start(/home/freaky/.rbenv/versions/jruby-9.0.1.0-SNAPSHOT/lib/ruby/gems/shared/gems/pry-0.10.1-java/lib/pry/pry_class.rb:169)
        28: bin.freshbsd.<top>(bin/freshbsd:32)
        29: java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:625)

**Comment by bartkamphorst** [comment]
Okay, it's been a while, but I can confirm the issue. It breaks on [this line](https://github.com/repotag/rjgit/blob/master/lib/commit.rb#L41). The `#get_parents` call seems to return okay, but when we try to map it to an actual commit it blows up.
```ruby
$ head.jcommit.get_parents
 => org.eclipse.jgit.revwalk.RevCommit[commit bbe3c31f66cbd6364dcd0ce4ed9b9ea2fcdfeb5b 0 ------]@209493bd 
```
and
```ruby
$ head.jcommit.get_parents.map{|x| RJGit::Commit.new(repo.jrepo, x)}
Java::JavaLang::NullPointerException: 
	from org.eclipse.jgit.util.RawParseUtils.author(org/eclipse/jgit/util/RawParseUtils.java:567)
	from org.eclipse.jgit.revwalk.RevCommit.getAuthorIdent(org/eclipse/jgit/revwalk/RevCommit.java:401)
	from java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)
	from RUBY.initialize(/Users/bart/.rvm/gems/jruby-1.7.19@repotag/gems/rjgit-4.0.3.0/lib/commit.rb:27)
	from RUBY.evaluate((irb):33)
```
