### ISSUE TITLE
RJGit::Porcelain#ls_tree does not traverse subdirectories if a tree is given

### ISSUE THREAD

**Issue by bartkamphorst** [repotag/rjgit#15]
The regression test is [here](https://github.com/repotag/rjgit/blob/master/spec/rjgit_spec.rb#L67-L76).

**Comment by bartkamphorst** [comment]
I've rewritten the `ls_tree` method from scratch, see [here](https://github.com/repotag/rjgit/blob/new_ls_tree/lib/rjgit.rb). The main advantages are that the new design makes much more sense (you now  call `ls_tree` with a `:ref` instead of a tree and an optional `path` and `options`) and that it resolves the issue at hand. There are, however, two problems with this approach. One, it breaks backward compatibility, and two, it seems to break `Tree#new_from_hashmap` for reasons I do not yet understand. The latter is a definite dealbreaker, the former just requires some tact about when and how to release the new code. Thoughts, @dometto ?

**Comment by dometto** [comment]
Much nicer implementation indeed, but no idea about why it would break new_from_hashmap. What error are you seeing exactly?

**Comment by bartkamphorst** [comment]
See [Travis](https://travis-ci.org/repotag/rjgit/jobs/93792479). What it seems to come down to is that it fails to find the new tree after it has been added.

**Comment by bartkamphorst** [comment]
Actually, the issue seems to be with `@tree.trees` and `@tree.blobs` which both call `#contents_array` (which uses `ls_tree`).

**Comment by dometto** [comment]
Ah, that should be fixable then. :)

**Comment by bartkamphorst** [comment]
The fix is in [this branch](https://github.com/repotag/rjgit/tree/new_ls_tree). I'm hesitant to merge into master though, as it breaks backward compatibility and we don't have a good semver structure in place. Thoughts?

**Comment by dometto** [comment]
Breaking backward compatibility is bad, but keeping bugs is worse I think. So unless we can think of a smart new versioning scheme that's compatible with semver *and* displays the JGit version numbering, I guess we should just release.
