### ISSUE TITLE
Git#revert options

### ISSUE THREAD

**Issue by dometto** [repotag/rjgit#21]
Can we implement a way to add path filters to `Git#revert`?

**Comment by bartkamphorst** [comment]
Not really, it seems. Revert really works on entire repo states. I think the way to do this is with a CheckoutCommand like so:
```java
git.checkout().setStartPoint("HEADˆ").addPath("file1.txt").call();
```
See also [this SO answer](http://stackoverflow.com/questions/2733873/reverting-a-single-file-to-a-previous-version-in-git).

**Comment by dometto** [comment]
Right, so we already support this behavior through `Git#checkout`. Thanks for solving my confusion. :)
