### ISSUE TITLE
No ssh transport available for clone_command (and others)

### ISSUE THREAD

**Issue by andersonmills** [repotag/rjgit#25]
I'm very interested in using the ssh transport for some git commands. I currently see an implementation of the UsernamePasswordCredentialsProvider, but no implementation of which would provide ssh transport.

Have y'all worked on this at all? It seems to be a deep well, as I dive in, involving implementing callbacks (org.eclipse.jgit.api.TransportConfigCallback), which I'm guessing might not be implementable in jruby, but need to be java directly.

I've been working on getting this implemented, and was just wondering where y'all stood with it.

Anderson

**Comment by bartkamphorst** [comment]
@andersonmills We haven't worked on this at all (I haven't anyway), but would welcome a PR that would add this functionality. I haven't investigated it closely, but I'm not sure dropping down to Java is strictly necessary, as I would think that creating a class that includes the TransportConfigCallback interface and implements `configure(transport)` might do the trick (but I might be off the mark here). Let us know how it goes!

**Comment by dometto** [comment]
Just a quick note: in jruby you can implement an interface as if it was a ruby module, so with `include org.jgit.Transport.Foo` in a class.

**Comment by andersonmills** [comment]
Okay, I've gotten it working with #27. I have a few questions there, and let me know what you think there as well.

**Comment by bartkamphorst** [comment]
Closed by https://github.com/repotag/rjgit/commit/d131fcb0b87e9bc0be6661bd9413e6d2438ddebf .
