### ISSUE TITLE
undefined method `objectId'

### ISSUE THREAD

**Issue by blablatros** [repotag/rjgit#30]
Please take a look at gollum/gollum/issues/1120

**Comment by dometto** [comment]
Thanks for the report and the proposed fix. Do you want to make a pull request out of it? Would be much appreciated. If necessary, please include a regression test (but I don't think that's necessary in this case).

**Comment by blablatros** [comment]
No problem, credit goes to @recomark1 for narrowing down the issue to `rjgit_helpers.rb`.

I've created a pull request - repotag/rjgit/pull/31

As for the regression test, I am afraid that is beyond me - I'm not a programmer.

**Comment by tism** [comment]
This also affects `blob.rb.find_blob`.

It appears to be a change in the 'ruby-ifying' of java methods between 1.7 and 9000.

1.7: `[:object_id, :get_object_id, :objectId]`
9000: `[:getObjectId, :get_object_id, :object_id]`

I'm surprised `objectId` was available in 1.7, but given the rest of the code seems to use the explicit getters I'd suggest `get_object_id` would be the suitable replacement.

**Comment by bartkamphorst** [comment]
Thanks @tism . Fixed in `master`.
