### ISSUE TITLE
Illegal reflective access operation

### ISSUE THREAD

**Issue by Freaky** [repotag/rjgit#59]
Seeing this on OpenJDK 14/15:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/home/freaky/.rbenv/versions/jruby-9.2.14.0/lib/ruby/gems/shared/gems/rjgit-5.9.0.1/lib/java/jars/bcprov-jdk15on-161.jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

This looks to be https://github.com/bcgit/bc-java/issues/510

**Comment by headius** [comment]
JRuby maintainer here... we asked @Freaky to file this because this error is similar to others we have fixed in JRuby, so we will get reports about this. I believe an upgrade to a new Bouncy Castle will fix this.

Let me know if you have any questions.

**Comment by bartkamphorst** [comment]
Thanks for the report, @Freaky and @headius . I'm working on resolving a couple of issues with the new JGit jar, but expect Bouncy Castle to be updated with the next RJGit release. 👍

**Comment by bartkamphorst** [comment]
RJGit version `5.10.0.0` was just released. @Freaky Can you confirm that the Illegal reflective access operation warning is gone?

**Comment by Freaky** [comment]
Confirmed, no more warning on OpenJDK 15 with the latest release.  Thanks!
